clc, clear;

%% ours
data_type = 'real_data';
for data_option = 4:9
  sprintf('data_option: %d', data_option)
  data_path = fullfile('data', data_type, strcat(data_type, '_', num2str(data_option)));
  if (~exist(data_path)) 
    continue;
  end
  params = load(fullfile(data_path, 'img/params.mat'));
  load(fullfile(data_path, 'result_lcecalib_qpep.mat'));
  TGt = params.TGt;
  save(fullfile(data_path, 'result_lcecalib_qpep.mat'), ...
    'data_type', 'data_option', ...
    'all_t_err', 'all_r_err', 'all_mp_err', 'all_me_err',...
    'select_t_err', 'select_r_err', 'select_mp_err', 'select_me_err', ...
    'all_eulerx', 'all_eulery', 'all_eulerz', ...
    'all_tx', 'all_ty', 'all_tz', ...
    'TGt', 'T_ini_best', 'T_est_best', ...
    'start_frame', ...
    'all_cam_board_corners', ...
    'all_cam_board_centers_on_plane', ...
    'all_cam_board_plane_coeff', ...
    'all_cam_board_plane_coeff_cov', ...
    'all_lidar_board_pts_raw', ...
    'all_lidar_board_pts', ...
    'all_lidar_board_edge_pts', ...
    'all_lidar_board_plane_coeff');

  load(fullfile(data_path, 'result_lcecalib_qpep_sensor_data.mat'));
  save(fullfile(data_path, 'result_lcecalib_qpep_sensor_data.mat'), ...
    'data_type', 'data_option', ...  
    'all_t_err', 'all_r_err', 'all_mp_err', 'all_me_err', ...
    'select_t_err', 'select_r_err', 'select_mp_err', 'select_me_err', ...
    'all_eulerx', 'all_eulery', 'all_eulerz', ...
    'all_tx', 'all_ty', 'all_tz', ...
    'TGt', 'T_ini_best', 'T_est_best', ...
    'start_frame', ...
    'all_cam_board_corners', ...
    'all_cam_board_centers_on_plane', ...
    'all_cam_board_plane_coeff', ...
    'all_cam_board_plane_coeff_cov', ...
    'all_lidar_board_pts_raw', ...
    'all_lidar_board_pts', ...
    'all_lidar_board_edge_pts', ...
    'all_lidar_board_plane_coeff', ...
    'all_img_undist', ...
    'all_lidar_pc_array', ...
    'all_lidar_pc_array_raw');
end

%% baseline zhou
data_type = 'real_data';
for data_option = 4:9
  sprintf('data_option: %d', data_option)
  data_path = fullfile('data', data_type, strcat(data_type, '_', num2str(data_option)));
  if (~exist(data_path)) 
    continue;
  end
  params = load(fullfile(data_path, 'img/params.mat'));
  load(fullfile(data_path, 'result_baseline_zhou.mat'));
  TGt = params.TGt;
  save(fullfile(data_path, 'result_baseline_zhou.mat'), ...
    'all_r_err', 'all_t_err', 'all_mp_err', 'all_me_err', ...
    'T_est_best', ...
    'all_lidar_board_plane_coeff');
  
  load(fullfile(data_path, 'result_baseline_zhou_sensor_data.mat'));
  save(fullfile(data_path, 'result_baseline_zhou_sensor_data.mat'), ...
    'all_r_err', 'all_t_err', 'all_mp_err', 'all_me_err', ...
    'T_est_best', ...
    'all_lidar_board_plane_coeff', ...
    'avail_lidarCheckerPlanes');  
end